# Generated by Django 5.2.1 on 2025-05-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ez', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ops', 'Operations'), ('client', 'Client')], default='client', max_length=10),
        ),
    ]
