# Generated by Django 5.2.1 on 2025-05-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ez', '0003_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='download_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
